version: 2
updates:
- package-ecosystem: gradle
  directory: "/Plan"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: com.djrapitops:Extension-ProtocolSupport
    versions:
    - ">= 4.a, < 5"
  - dependency-name: com.djrapitops:Extension-Tebex
    versions:
    - "> R0.6"
  - dependency-name: com.h2database:h2
    versions:
    - "> 1.4.199"
